language: node_js
node_js: "12"

cache: yarn

jobs:
  include:
    # Define the release stage that runs semantic-release
    - stage: release
      if: branch = master
      node_js: lts/*
      # Advanced: optionally overwrite your default `script` step to skip the tests
      # script: skip
      before_script:
        - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
        - chmod +x ./cc-test-reporter
        - ./cc-test-reporter before-build
      deploy:
        provider: script
        skip_cleanup: true
        script: yarn semantic-release --allow-same-version
      after_script:
        - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
