language: node_js
node_js: "12"
os: "linux"

cache: yarn

install: yarn install

jobs:
  include:
    - stage: npm release
      if: tag IS present
      node_js: stable
      script: yarn build
      deploy:
        provider: npm
        email: "$NPM_EMAIL"
        api_key: "$NPM_TOKEN"
        tag: latest
        on:
          tags: true
